### ISSUE TITLE
GFM line breaks

### ISSUE THREAD

**Issue by am97** [billthefarmer/MarkdownView#1]
Pleaae add support for [GFM](https://help.github.com/categories/writing-on-github/) style line breaks 
I use markdown all the time in your Diary app, I would like to be able to type a new line without having to write two spaces at the end, because this is very inconvenient.
Here is a link showing how the issue was solved in another project: https://github.com/chjj/marked/issues/51

**Comment by billthefarmer** [comment]
This project uses [markdownj](https://github.com/myabc/markdownj) for markdown functionality and is just a wrapper around a [WebView](https://developer.android.com/reference/android/webkit/WebView.html). Markdownj is just an implementation of the original Markdown in Java. There isn't any markdown interpretation in here. If you want Github flavoured markdown you are welcome to fork the project, or the [one I forked it from](https://github.com/falnatsheh/MarkdownView), and use a different markdown interpreter.

[RTRM](https://github.com/billthefarmer/MarkdownView/blob/master/README.md)
